import type { NextPage } from "next";
import Head from "next/head";
import { client } from "../apollo-client";
import { Team, TeamsDocument } from "../generated/graphql";

const Home: NextPage<{ teams: Team[] }> = ({ teams }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {JSON.stringify(teams)}
    </div>
  );
};

// pages/index.js
export async function getStaticProps() {
  const { data } = await client.query({
    query: TeamsDocument,
  });

  return {
    props: {
      teams: data.teams,
    },
  };
}

export default Home;
