query Teams {
  teams {
    teamCode
    golds
    finals
    founded
    holyNumbers
  }
}

query GameDays($input: StatisticsInput!) {
  gameDays(input: $input) {
    date
    games {
      gameId
      time
      date
      homeTeamCode
      homeTeamName
      awayTeamCode
      awayTeamName
      result
    }
  }
}

query Standings($input: StatisticsInput!) {
  standings(input: $input) {
    teamId
    teamCode
    teamName
    goals
    goalsAgainst
    onePoints
    plusMinus
    rank
    threePoints
    twoPoints
    zeroPoints
    points
  }
}

query Goalies($input: GoaliesInput!) {
  goalies(input: $input) {
    playerId
    firstName
    lastName
    goalsAgainst
  }
}

query Skaters($input: SkatersInput!) {
  skaters(input: $input) {
    playerId
    firstName
    lastName
    goals
  }
}
