query Teams {
  teams {
    teamCode
    golds
    finals
    founded
    holyNumbers
  }
}

query Games($input: StatisticsInput!) {
  games(input: $input) {
    gameId
    time
    away
    home
    result
  }
}

query Standings($input: StatisticsInput!) {
  standings(input: $input) {
    teamCode
    goals
    goalsAgainst
    onePoints
    plusMinus
    rank
    threePoints
    twoPoints
    zeroPoints
    points
  }
}
